
#ifndef XtremeFunction1_h
#define XtremeFunction1_h

#include "ArrayList.h"
#include "ModifiableFunction.h"

class XtremeFunction1 : public ModifiableFunction<float,float>{
	public:
		
		XtremeFunction1(){
			this->constants = new ArrayList<float,20>;
			this->variables = new ArrayList<float,200>;
			for(int x=0; x <= 20; x++){
				this->constants->addPointer(new float(0.0f));
			}
			for(int x=0; x <= 200; x++){
				this->variables->addPointer(new float(0.0f));
			}
		}
		
		virtual ~XtremeFunction1(){
			delete this->constants;
			delete this->variables;
		}
    
		//cppObject part
		String getClassName(){
			return "XtremeFunction1";
		}
		String toString(){
			return "XtremeFunction1";
		}
		virtual float f(float x){
			return 	(*this->constants->getByPosition(0)) * (*this->variables->getByPosition(0) ) * x - (*this->constants->getByPosition(0)) * (*this->variables->getByPosition(1) ) *x +  (*this->variables->getByPosition(2) ) *x -  (*this->variables->getByPosition(3) ) *x + (*this->constants->getByPosition(0)) * (*this->variables->getByPosition(4) ) *x*x - (*this->constants->getByPosition(0)) * (*this->variables->getByPosition(5) ) *x*x + (*this->constants->getByPosition(0)) * (*this->variables->getByPosition(6) )  - (*this->constants->getByPosition(0)) * (*this->variables->getByPosition(7) ) +  (*this->variables->getByPosition(8) )  *  (*this->variables->getByPosition(9) ) +
					(*this->constants->getByPosition(1)) * (*this->variables->getByPosition(10)) * x - (*this->constants->getByPosition(1)) * (*this->variables->getByPosition(11)) *x +  (*this->variables->getByPosition(12)) *x -  (*this->variables->getByPosition(13)) *x + (*this->constants->getByPosition(1)) * (*this->variables->getByPosition(14)) *x*x - (*this->constants->getByPosition(1)) * (*this->variables->getByPosition(15)) *x*x + (*this->constants->getByPosition(1)) * (*this->variables->getByPosition(16))  - (*this->constants->getByPosition(1)) * (*this->variables->getByPosition(17)) +  (*this->variables->getByPosition(18))  *  (*this->variables->getByPosition(19)) +
					(*this->constants->getByPosition(2)) * (*this->variables->getByPosition(20)) * x - (*this->constants->getByPosition(2)) * (*this->variables->getByPosition(21)) *x +  (*this->variables->getByPosition(22)) *x -  (*this->variables->getByPosition(23)) *x + (*this->constants->getByPosition(2)) * (*this->variables->getByPosition(24)) *x*x - (*this->constants->getByPosition(2)) * (*this->variables->getByPosition(25)) *x*x + (*this->constants->getByPosition(2)) * (*this->variables->getByPosition(26))  - (*this->constants->getByPosition(2)) * (*this->variables->getByPosition(27)) +  (*this->variables->getByPosition(28))  *  (*this->variables->getByPosition(29)) +
					(*this->constants->getByPosition(3)) * (*this->variables->getByPosition(30)) * x - (*this->constants->getByPosition(3)) * (*this->variables->getByPosition(31)) *x +  (*this->variables->getByPosition(32)) *x -  (*this->variables->getByPosition(33)) *x + (*this->constants->getByPosition(3)) * (*this->variables->getByPosition(34)) *x*x - (*this->constants->getByPosition(3)) * (*this->variables->getByPosition(35)) *x*x + (*this->constants->getByPosition(3)) * (*this->variables->getByPosition(36))  - (*this->constants->getByPosition(3)) * (*this->variables->getByPosition(37)) +  (*this->variables->getByPosition(38))  *  (*this->variables->getByPosition(39)) +
					(*this->constants->getByPosition(4)) * (*this->variables->getByPosition(40)) * x - (*this->constants->getByPosition(4)) * (*this->variables->getByPosition(41)) *x +  (*this->variables->getByPosition(42)) *x -  (*this->variables->getByPosition(43)) *x + (*this->constants->getByPosition(4)) * (*this->variables->getByPosition(44)) *x*x - (*this->constants->getByPosition(4)) * (*this->variables->getByPosition(45)) *x*x + (*this->constants->getByPosition(4)) * (*this->variables->getByPosition(46))  - (*this->constants->getByPosition(4)) * (*this->variables->getByPosition(47)) +  (*this->variables->getByPosition(48))  *  (*this->variables->getByPosition(49)) +
					(*this->constants->getByPosition(5)) * (*this->variables->getByPosition(50)) * x - (*this->constants->getByPosition(5)) * (*this->variables->getByPosition(51)) *x +  (*this->variables->getByPosition(52)) *x -  (*this->variables->getByPosition(53)) *x + (*this->constants->getByPosition(5)) * (*this->variables->getByPosition(54)) *x*x - (*this->constants->getByPosition(5)) * (*this->variables->getByPosition(55)) *x*x + (*this->constants->getByPosition(5)) * (*this->variables->getByPosition(56))  - (*this->constants->getByPosition(5)) * (*this->variables->getByPosition(57)) +  (*this->variables->getByPosition(58))  *  (*this->variables->getByPosition(59)) +
					(*this->constants->getByPosition(6)) * (*this->variables->getByPosition(60)) * x - (*this->constants->getByPosition(6)) * (*this->variables->getByPosition(61)) *x +  (*this->variables->getByPosition(62)) *x -  (*this->variables->getByPosition(63)) *x + (*this->constants->getByPosition(6)) * (*this->variables->getByPosition(64)) *x*x - (*this->constants->getByPosition(6)) * (*this->variables->getByPosition(65)) *x*x + (*this->constants->getByPosition(6)) * (*this->variables->getByPosition(66))  - (*this->constants->getByPosition(6)) * (*this->variables->getByPosition(67)) +  (*this->variables->getByPosition(68))  *  (*this->variables->getByPosition(69)) +
					(*this->constants->getByPosition(7)) * (*this->variables->getByPosition(70)) * x - (*this->constants->getByPosition(7)) * (*this->variables->getByPosition(71)) *x +  (*this->variables->getByPosition(72)) *x -  (*this->variables->getByPosition(73)) *x + (*this->constants->getByPosition(7)) * (*this->variables->getByPosition(74)) *x*x - (*this->constants->getByPosition(7)) * (*this->variables->getByPosition(75)) *x*x + (*this->constants->getByPosition(7)) * (*this->variables->getByPosition(76))  - (*this->constants->getByPosition(7)) * (*this->variables->getByPosition(77)) +  (*this->variables->getByPosition(78))  *  (*this->variables->getByPosition(79)) +
					(*this->constants->getByPosition(8)) * (*this->variables->getByPosition(80)) * x - (*this->constants->getByPosition(8)) * (*this->variables->getByPosition(81)) *x +  (*this->variables->getByPosition(82)) *x -  (*this->variables->getByPosition(83)) *x + (*this->constants->getByPosition(8)) * (*this->variables->getByPosition(84)) *x*x - (*this->constants->getByPosition(8)) * (*this->variables->getByPosition(85)) *x*x + (*this->constants->getByPosition(8)) * (*this->variables->getByPosition(86))  - (*this->constants->getByPosition(8)) * (*this->variables->getByPosition(87)) +  (*this->variables->getByPosition(88))  *  (*this->variables->getByPosition(89)) +
					(*this->constants->getByPosition(9)) * (*this->variables->getByPosition(90)) * x - (*this->constants->getByPosition(9)) * (*this->variables->getByPosition(91)) *x +  (*this->variables->getByPosition(92)) *x -  (*this->variables->getByPosition(93)) *x + (*this->constants->getByPosition(9)) * (*this->variables->getByPosition(94)) *x*x - (*this->constants->getByPosition(9)) * (*this->variables->getByPosition(95)) *x*x + (*this->constants->getByPosition(9)) * (*this->variables->getByPosition(96))  - (*this->constants->getByPosition(9)) * (*this->variables->getByPosition(97)) +  (*this->variables->getByPosition(98))  *  (*this->variables->getByPosition(99)) +
					
					(*this->constants->getByPosition(10)) * (*this->variables->getByPosition(100)) * x - (*this->constants->getByPosition(10)) * (*this->variables->getByPosition(101)) *x +  (*this->variables->getByPosition(102)) *x -  (*this->variables->getByPosition(103)) *x + (*this->constants->getByPosition(10)) * (*this->variables->getByPosition(104)) *x*x - (*this->constants->getByPosition(10)) * (*this->variables->getByPosition(105)) *x*x + (*this->constants->getByPosition(10)) * (*this->variables->getByPosition(106))  - (*this->constants->getByPosition(10)) * (*this->variables->getByPosition(107)) +  (*this->variables->getByPosition(108))  *  (*this->variables->getByPosition(109)) +
					(*this->constants->getByPosition(11)) * (*this->variables->getByPosition(110)) * x - (*this->constants->getByPosition(11)) * (*this->variables->getByPosition(111)) *x +  (*this->variables->getByPosition(112)) *x -  (*this->variables->getByPosition(113)) *x + (*this->constants->getByPosition(11)) * (*this->variables->getByPosition(114)) *x*x - (*this->constants->getByPosition(11)) * (*this->variables->getByPosition(115)) *x*x + (*this->constants->getByPosition(11)) * (*this->variables->getByPosition(116))  - (*this->constants->getByPosition(11)) * (*this->variables->getByPosition(117)) +  (*this->variables->getByPosition(118))  *  (*this->variables->getByPosition(119)) +
					(*this->constants->getByPosition(12)) * (*this->variables->getByPosition(120)) * x - (*this->constants->getByPosition(12)) * (*this->variables->getByPosition(121)) *x +  (*this->variables->getByPosition(122)) *x -  (*this->variables->getByPosition(123)) *x + (*this->constants->getByPosition(12)) * (*this->variables->getByPosition(124)) *x*x - (*this->constants->getByPosition(12)) * (*this->variables->getByPosition(125)) *x*x + (*this->constants->getByPosition(12)) * (*this->variables->getByPosition(126))  - (*this->constants->getByPosition(12)) * (*this->variables->getByPosition(127)) +  (*this->variables->getByPosition(128))  *  (*this->variables->getByPosition(129)) +
					(*this->constants->getByPosition(13)) * (*this->variables->getByPosition(130)) * x - (*this->constants->getByPosition(13)) * (*this->variables->getByPosition(131)) *x +  (*this->variables->getByPosition(132)) *x -  (*this->variables->getByPosition(133)) *x + (*this->constants->getByPosition(13)) * (*this->variables->getByPosition(134)) *x*x - (*this->constants->getByPosition(13)) * (*this->variables->getByPosition(135)) *x*x + (*this->constants->getByPosition(13)) * (*this->variables->getByPosition(136))  - (*this->constants->getByPosition(13)) * (*this->variables->getByPosition(137)) +  (*this->variables->getByPosition(138))  *  (*this->variables->getByPosition(139)) +
					(*this->constants->getByPosition(14)) * (*this->variables->getByPosition(140)) * x - (*this->constants->getByPosition(14)) * (*this->variables->getByPosition(141)) *x +  (*this->variables->getByPosition(142)) *x -  (*this->variables->getByPosition(143)) *x + (*this->constants->getByPosition(14)) * (*this->variables->getByPosition(144)) *x*x - (*this->constants->getByPosition(14)) * (*this->variables->getByPosition(145)) *x*x + (*this->constants->getByPosition(14)) * (*this->variables->getByPosition(146))  - (*this->constants->getByPosition(14)) * (*this->variables->getByPosition(147)) +  (*this->variables->getByPosition(148))  *  (*this->variables->getByPosition(149)) +
					(*this->constants->getByPosition(15)) * (*this->variables->getByPosition(150)) * x - (*this->constants->getByPosition(15)) * (*this->variables->getByPosition(151)) *x +  (*this->variables->getByPosition(152)) *x -  (*this->variables->getByPosition(153)) *x + (*this->constants->getByPosition(15)) * (*this->variables->getByPosition(154)) *x*x - (*this->constants->getByPosition(15)) * (*this->variables->getByPosition(155)) *x*x + (*this->constants->getByPosition(15)) * (*this->variables->getByPosition(156))  - (*this->constants->getByPosition(15)) * (*this->variables->getByPosition(157)) +  (*this->variables->getByPosition(158))  *  (*this->variables->getByPosition(159)) +
					(*this->constants->getByPosition(16)) * (*this->variables->getByPosition(160)) * x - (*this->constants->getByPosition(16)) * (*this->variables->getByPosition(161)) *x +  (*this->variables->getByPosition(162)) *x -  (*this->variables->getByPosition(163)) *x + (*this->constants->getByPosition(16)) * (*this->variables->getByPosition(164)) *x*x - (*this->constants->getByPosition(16)) * (*this->variables->getByPosition(165)) *x*x + (*this->constants->getByPosition(16)) * (*this->variables->getByPosition(166))  - (*this->constants->getByPosition(16)) * (*this->variables->getByPosition(167)) +  (*this->variables->getByPosition(168))  *  (*this->variables->getByPosition(169)) +
					(*this->constants->getByPosition(17)) * (*this->variables->getByPosition(170)) * x - (*this->constants->getByPosition(17)) * (*this->variables->getByPosition(171)) *x +  (*this->variables->getByPosition(172)) *x -  (*this->variables->getByPosition(173)) *x + (*this->constants->getByPosition(17)) * (*this->variables->getByPosition(174)) *x*x - (*this->constants->getByPosition(17)) * (*this->variables->getByPosition(175)) *x*x + (*this->constants->getByPosition(17)) * (*this->variables->getByPosition(176))  - (*this->constants->getByPosition(17)) * (*this->variables->getByPosition(177)) +  (*this->variables->getByPosition(178))  *  (*this->variables->getByPosition(179)) +
					(*this->constants->getByPosition(18)) * (*this->variables->getByPosition(180)) * x - (*this->constants->getByPosition(18)) * (*this->variables->getByPosition(181)) *x +  (*this->variables->getByPosition(182)) *x -  (*this->variables->getByPosition(183)) *x + (*this->constants->getByPosition(18)) * (*this->variables->getByPosition(184)) *x*x - (*this->constants->getByPosition(18)) * (*this->variables->getByPosition(185)) *x*x + (*this->constants->getByPosition(18)) * (*this->variables->getByPosition(186))  - (*this->constants->getByPosition(18)) * (*this->variables->getByPosition(187)) +  (*this->variables->getByPosition(188))  *  (*this->variables->getByPosition(189)) +
					(*this->constants->getByPosition(19)) * (*this->variables->getByPosition(190)) * x - (*this->constants->getByPosition(19)) * (*this->variables->getByPosition(191)) *x +  (*this->variables->getByPosition(192)) *x -  (*this->variables->getByPosition(193)) *x + (*this->constants->getByPosition(19)) * (*this->variables->getByPosition(194)) *x*x - (*this->constants->getByPosition(19)) * (*this->variables->getByPosition(195)) *x*x + (*this->constants->getByPosition(19)) * (*this->variables->getByPosition(196))  - (*this->constants->getByPosition(19)) * (*this->variables->getByPosition(197)) +  (*this->variables->getByPosition(198))  *  (*this->variables->getByPosition(199))
					
					;
		}
		
		virtual int getIterationSize(){
			return 200;
		}
		virtual bool instanceof(String name){return name == "XtremeFunction1" || name == "ModifiableFunction" || name == "Function";}
		
	protected:
		
		
	
};

#endif 
